[phases.setup]
nixPkgs = ["chromium", "glib", "nss", "nspr", "atk", "at-spi2-atk", "libdrm", "libxkbcommon", "pango", "cairo", "libX11", "libXcomposite", "libXdamage", "libXext", "libXfixes", "libXrandr", "libgbm", "alsa-lib"]

[phases.build]
cmds = ["npm install", "npx prisma generate"]
